name: backend CI/CD
on:
  push:
    branches:
      - "master"
    paths:
      - '*'
  pull_request:
    branches:
      - "master"
    paths:
      - '*'
  workflow_dispatch:  # Add this to enable manual triggering

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Debug Information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Runner hostname: $(hostname)"
          echo "Current user: $(whoami)"
          echo "Working directory: $(pwd)"
          node -v
          npm -v
      
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Use Node.js
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      # Cache node_modules
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      
      # Install dependencies
      - name: Install dependencies
        run: npm install
      
      # Build project
      - name: Build project
        run: npm run build
      
      # Restart ai-backend using PM2
      - name: Restart backend
        run: pm2 restart ai-backend
